language: node_js

node_js:
  - "9.3.0"

services: mysql

cache:
  directories:
    - "node_modules"
  yarn: true

env:
  - SECRET=somesecretword

before_install:
  - "cp config/config.travis.json config/config.json"
  - "mysql -e 'CREATE DATABASE database_test;'"
  - "npm install"
  - "sequelize --env test db:migrate"
  - "sequelize --env test db:seed --seed seeders/20180118112739-seed-test-user.js "

script:
  - "npm run test"
  - "eslint ./* --quiet"