language: node_js

node_js:
  - "9.3.0"

services: postgresql

cache:
  directories:
    - "node_modules"
  yarn: true

env:
  - SECRET=somesecretword

before_install:
  - "cp config/config.travis.json config/config.json"
  - psql -c 'create database database_test;' -U postgres  
  - "npm install"
  - "sequelize --env test db:migrate"
  - "sequelize --env test db:seed --seed seeders/20180118112739-seed-test-user.js "
  - "sequelize --env test db:seed --seed seeders/20180305092818-create_sender.js "

script:
  - "npm run test"
  - "eslint ./* --quiet"